### ISSUE TITLE
Potential incorrect moderator message count

### ISSUE THREAD

**Issue by StaticEssence** [r-smashbros/setsudo#7]
Index is showing in the moderator message count; despite having resigned over a month ago and the count being reset several times since then.

**Comment by SirPacker** [comment]
While this issue would normally need to be addressed, PR #6 changes how moderator voting activity is processed and displayed. The redesign should prevent such things from happening (as tests have shown), but I'll be sure to keep an eye out for any similar issues popping up.

(This issue will be closed upon the merging of PR #6)
